import './globals.css'
import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import Navbar from '../../components/navbar'

// const inter = Inter({ subsets: ['latin'] })

// import Providers from "@/redus/provider"
import AppState from './context/appState'
export const metadata: Metadata = {
  title: 'YouTube Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <AppState>
        <Navbar /> {children} 
        </AppState>
        </body>
    </html>
  )
}
